# Generated by Django 6.1 on 2026-08-17 05:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_maintenancereport_priority_maintenancereport_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frequency', models.PositiveIntegerField(help_text='How often maintenance should occur.')),
                ('frequency_unit', models.CharField(choices=[('DAYS', 'Days'), ('WEEKS', 'Weeks'), ('MONTHS', 'Months'), ('YEARS', 'Years')], max_length=10)),
                ('next_maintenance_date', models.DateField()),
                ('last_maintenance_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asset', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_schedule', to='api.asset')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='maintenance_schedules_created', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
