# Generated by Django 6.1 on 2026-08-17 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_maintenanceschedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenanceschedule',
            name='next_maintenance_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
