# Generated by Django 6.1 on 2026-08-17 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_maintenanceschedule_next_maintenance_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenancereport',
            name='review_comment',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='maintenancereport',
            name='review_status',
            field=models.CharField(choices=[('PENDING', 'Pending Review'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20),
        ),
        migrations.AddField(
            model_name='maintenancereport',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
