# Generated by Django 6.1 on 2026-08-17 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_maintenancereport_review_comment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenancereport',
            name='reassignment_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='maintenancereport',
            name='requires_admin_action',
            field=models.BooleanField(default=False),
        ),
    ]
