# Generated by Django 6.1 on 2026-08-19 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_workorder_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenancereport',
            name='review_comment',
            field=models.TextField(blank=True, default=''),
        ),
    ]
