# Generated by Django 6.1 on 2026-08-26 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0011_alter_maintenancereport_review_comment"),
    ]

    operations = [
        migrations.AddField(
            model_name="workorder",
            name="client_responded_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="workorder",
            name="client_response",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending Response"),
                    ("ACCEPTED", "Accepted"),
                    ("REJECTED", "Rejected"),
                ],
                default="PENDING",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="workorder",
            name="client_response_comment",
            field=models.TextField(blank=True, default=""),
        ),
    ]
