# Generated by Django 6.1 on 2026-09-16 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_workorder_client_responded_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuoteRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('company_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('package', models.CharField(choices=[('STARTER', 'Starter'), ('BUSINESS', 'Business'), ('ENTERPRISE', 'Enterprise')], max_length=20)),
                ('number_of_assets', models.PositiveIntegerField(blank=True, null=True)),
                ('number_of_users', models.PositiveIntegerField(blank=True, null=True)),
                ('requirements', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('NEW', 'New'), ('CONTACTED', 'Contacted'), ('QUOTED', 'Quoted'), ('ACCEPTED', 'Accepted'), ('DECLINED', 'Declined')], default='NEW', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
